### ISSUE TITLE
Is the Rotor mono?

### ISSUE THREAD

**Issue by KottV** [maxwellmattryan/rotor#1]
Hi,

Thank You for great plugin. I've compiled it and found that it accepts only left channel, is that supposed to be?

**Comment by maxwellmattryan** [comment]
Hey Konstantin,

Thanks! The plugin is _supposed_ to be in stereo, so it should be accepting both LR channels. The version of the plugin I'm using is working, but I will need to try a rebuild later to see if that issue pops up. My guess is maybe there is some configuration that is wrong within the JUCER? 

I will be able to hop on it today / tomorrow so I can see what's up! Thanks for letting me know.

**Comment by KottV** [comment]
Well,

It was tested under Linux. Now I'm available to test on Windows and downloaded binary is the left-channel-only too.

**Comment by maxwellmattryan** [comment]
Hey Konstantin,

I'm sorry for the super delayed response. I've finally had some time to look at it and it definitely is in mono. I'm only ever reading the 0th channel and setting that processed value to both. I will be sure to fix this tomorrow! I'll let you know when I do 👍

**Comment by KottV** [comment]
No worries,
Glad that You've found it )

**Comment by maxwellmattryan** [comment]
So I just updated the repository - should all be good now! Thanks again for pointing this out. If you come across anything else, I'd love to hear about it!
